// This file was generated by counterfeiter
package fakes

import (
	. "github.com/cloudfoundry/cli/cf/api/application_bits"
	"github.com/cloudfoundry/cli/cf/api/resources"
	"github.com/cloudfoundry/cli/cf/models"

	"os"
	"sync"
)

type FakeApplicationBitsRepository struct {
	GetApplicationFilesStub        func(appFilesRequest []models.AppFileFields) ([]models.AppFileFields, error)
	getApplicationFilesMutex       sync.RWMutex
	getApplicationFilesArgsForCall []struct {
		appFilesRequest []models.AppFileFields
	}
	getApplicationFilesReturns struct {
		result1 []models.AppFileFields
		result2 error
	}
	UploadBitsStub        func(appGuid string, zipFile *os.File, presentFiles []resources.AppFileResource) (apiErr error)
	uploadBitsMutex       sync.RWMutex
	uploadBitsArgsForCall []struct {
		appGuid      string
		zipFile      *os.File
		presentFiles []resources.AppFileResource
	}
	uploadBitsReturns struct {
		result1 error
	}
}

func (fake *FakeApplicationBitsRepository) GetApplicationFiles(appFilesRequest []models.AppFileFields) ([]models.AppFileFields, error) {
	fake.getApplicationFilesMutex.Lock()
	defer fake.getApplicationFilesMutex.Unlock()
	fake.getApplicationFilesArgsForCall = append(fake.getApplicationFilesArgsForCall, struct {
		appFilesRequest []models.AppFileFields
	}{appFilesRequest})
	if fake.GetApplicationFilesStub != nil {
		return fake.GetApplicationFilesStub(appFilesRequest)
	} else {
		return fake.getApplicationFilesReturns.result1, fake.getApplicationFilesReturns.result2
	}
}

func (fake *FakeApplicationBitsRepository) GetApplicationFilesCallCount() int {
	fake.getApplicationFilesMutex.RLock()
	defer fake.getApplicationFilesMutex.RUnlock()
	return len(fake.getApplicationFilesArgsForCall)
}

func (fake *FakeApplicationBitsRepository) GetApplicationFilesArgsForCall(i int) []models.AppFileFields {
	fake.getApplicationFilesMutex.RLock()
	defer fake.getApplicationFilesMutex.RUnlock()
	return fake.getApplicationFilesArgsForCall[i].appFilesRequest
}

func (fake *FakeApplicationBitsRepository) GetApplicationFilesReturns(result1 []models.AppFileFields, result2 error) {
	fake.getApplicationFilesReturns = struct {
		result1 []models.AppFileFields
		result2 error
	}{result1, result2}
}

func (fake *FakeApplicationBitsRepository) UploadBits(appGuid string, zipFile *os.File, presentFiles []resources.AppFileResource) (apiErr error) {
	fake.uploadBitsMutex.Lock()
	defer fake.uploadBitsMutex.Unlock()
	fake.uploadBitsArgsForCall = append(fake.uploadBitsArgsForCall, struct {
		appGuid      string
		zipFile      *os.File
		presentFiles []resources.AppFileResource
	}{appGuid, zipFile, presentFiles})
	if fake.UploadBitsStub != nil {
		return fake.UploadBitsStub(appGuid, zipFile, presentFiles)
	} else {
		return fake.uploadBitsReturns.result1
	}
}

func (fake *FakeApplicationBitsRepository) UploadBitsCallCount() int {
	fake.uploadBitsMutex.RLock()
	defer fake.uploadBitsMutex.RUnlock()
	return len(fake.uploadBitsArgsForCall)
}

func (fake *FakeApplicationBitsRepository) UploadBitsArgsForCall(i int) (string, *os.File, []resources.AppFileResource) {
	fake.uploadBitsMutex.RLock()
	defer fake.uploadBitsMutex.RUnlock()
	return fake.uploadBitsArgsForCall[i].appGuid, fake.uploadBitsArgsForCall[i].zipFile, fake.uploadBitsArgsForCall[i].presentFiles
}

func (fake *FakeApplicationBitsRepository) UploadBitsReturns(result1 error) {
	fake.uploadBitsReturns = struct {
		result1 error
	}{result1}
}

var _ ApplicationBitsRepository = new(FakeApplicationBitsRepository)
